# Welcome to Serverless!
service: serverless-example
app: product-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  productAPI:
    package:
      include:
        - dataset/flyers_data.csv
    handler: Controller/products.handler
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
